package com.tmdrk.chat.dao.mapper;

import com.tmdrk.chat.dao.entity.ChatUser;
import com.tmdrk.chat.dao.entity.ChatUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ChatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int countByExample(ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int deleteByExample(ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int insert(ChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int insertSelective(ChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    List<ChatUser> selectByExample(ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    ChatUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") ChatUser record, @Param("example") ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int updateByExample(@Param("record") ChatUser record, @Param("example") ChatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ChatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int updateByPrimaryKey(ChatUser record);
}