package com.tmdrk.chat.dao.mapper;

import com.tmdrk.chat.dao.entity.ChatUserMessage;
import com.tmdrk.chat.dao.entity.ChatUserMessageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ChatUserMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER_MESSAGE
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int countByExample(ChatUserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER_MESSAGE
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int deleteByExample(ChatUserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER_MESSAGE
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER_MESSAGE
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int insert(ChatUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER_MESSAGE
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int insertSelective(ChatUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER_MESSAGE
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    List<ChatUserMessage> selectByExample(ChatUserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER_MESSAGE
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    ChatUserMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER_MESSAGE
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") ChatUserMessage record, @Param("example") ChatUserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER_MESSAGE
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int updateByExample(@Param("record") ChatUserMessage record, @Param("example") ChatUserMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER_MESSAGE
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ChatUserMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHAT_USER_MESSAGE
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    int updateByPrimaryKey(ChatUserMessage record);
}