package com.tmdrk.ace.admin.entity;

public class AceMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACE_MENU.menu_id
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACE_MENU.menu_name
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACE_MENU.menu_desc
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    private String menuDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACE_MENU.menu_url
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACE_MENU.parent_menu_id
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    private Integer parentMenuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACE_MENU.weight
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACE_MENU.menu_icon
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    private String menuIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACE_MENU.menu_id
     *
     * @return the value of ACE_MENU.menu_id
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACE_MENU.menu_id
     *
     * @param menuId the value for ACE_MENU.menu_id
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACE_MENU.menu_name
     *
     * @return the value of ACE_MENU.menu_name
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACE_MENU.menu_name
     *
     * @param menuName the value for ACE_MENU.menu_name
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACE_MENU.menu_desc
     *
     * @return the value of ACE_MENU.menu_desc
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACE_MENU.menu_desc
     *
     * @param menuDesc the value for ACE_MENU.menu_desc
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc == null ? null : menuDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACE_MENU.menu_url
     *
     * @return the value of ACE_MENU.menu_url
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACE_MENU.menu_url
     *
     * @param menuUrl the value for ACE_MENU.menu_url
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACE_MENU.parent_menu_id
     *
     * @return the value of ACE_MENU.parent_menu_id
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public Integer getParentMenuId() {
        return parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACE_MENU.parent_menu_id
     *
     * @param parentMenuId the value for ACE_MENU.parent_menu_id
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public void setParentMenuId(Integer parentMenuId) {
        this.parentMenuId = parentMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACE_MENU.weight
     *
     * @return the value of ACE_MENU.weight
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACE_MENU.weight
     *
     * @param weight the value for ACE_MENU.weight
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACE_MENU.menu_icon
     *
     * @return the value of ACE_MENU.menu_icon
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACE_MENU.menu_icon
     *
     * @param menuIcon the value for ACE_MENU.menu_icon
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon == null ? null : menuIcon.trim();
    }
}