package com.tmdrk.ace.admin.entity;

import java.util.Date;

public class OmpAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.id
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.tenant_id
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.platform
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.code
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.name
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.short_name
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.parent_code
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.path_name
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private String pathName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.level
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.mapper_id
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private Integer mapperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.is_del
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.created_by
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.created_time
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.update_by
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column omp_address.update_time
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.id
     *
     * @return the value of omp_address.id
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.id
     *
     * @param id the value for omp_address.id
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.tenant_id
     *
     * @return the value of omp_address.tenant_id
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.tenant_id
     *
     * @param tenantId the value for omp_address.tenant_id
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.platform
     *
     * @return the value of omp_address.platform
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.platform
     *
     * @param platform the value for omp_address.platform
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.code
     *
     * @return the value of omp_address.code
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.code
     *
     * @param code the value for omp_address.code
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.name
     *
     * @return the value of omp_address.name
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.name
     *
     * @param name the value for omp_address.name
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.short_name
     *
     * @return the value of omp_address.short_name
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.short_name
     *
     * @param shortName the value for omp_address.short_name
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.parent_code
     *
     * @return the value of omp_address.parent_code
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.parent_code
     *
     * @param parentCode the value for omp_address.parent_code
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.path_name
     *
     * @return the value of omp_address.path_name
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public String getPathName() {
        return pathName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.path_name
     *
     * @param pathName the value for omp_address.path_name
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setPathName(String pathName) {
        this.pathName = pathName == null ? null : pathName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.level
     *
     * @return the value of omp_address.level
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.level
     *
     * @param level the value for omp_address.level
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.mapper_id
     *
     * @return the value of omp_address.mapper_id
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public Integer getMapperId() {
        return mapperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.mapper_id
     *
     * @param mapperId the value for omp_address.mapper_id
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setMapperId(Integer mapperId) {
        this.mapperId = mapperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.is_del
     *
     * @return the value of omp_address.is_del
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.is_del
     *
     * @param isDel the value for omp_address.is_del
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.created_by
     *
     * @return the value of omp_address.created_by
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.created_by
     *
     * @param createdBy the value for omp_address.created_by
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.created_time
     *
     * @return the value of omp_address.created_time
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.created_time
     *
     * @param createdTime the value for omp_address.created_time
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.update_by
     *
     * @return the value of omp_address.update_by
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.update_by
     *
     * @param updateBy the value for omp_address.update_by
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column omp_address.update_time
     *
     * @return the value of omp_address.update_time
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column omp_address.update_time
     *
     * @param updateTime the value for omp_address.update_time
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}