package com.tmdrk.shiro.mapper;

import com.tmdrk.shiro.entity.AclPermission;
import com.tmdrk.shiro.entity.AclPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AclPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int countByExample(AclPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int deleteByExample(AclPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int insert(AclPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int insertSelective(AclPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    List<AclPermission> selectByExample(AclPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    AclPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") AclPermission record, @Param("example") AclPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int updateByExample(@Param("record") AclPermission record, @Param("example") AclPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(AclPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int updateByPrimaryKey(AclPermission record);
}