package com.tmdrk.shiro.mapper;

import com.tmdrk.shiro.entity.AclRolePermission;
import com.tmdrk.shiro.entity.AclRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AclRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int countByExample(AclRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int deleteByExample(AclRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int insert(AclRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int insertSelective(AclRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    List<AclRolePermission> selectByExample(AclRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    AclRolePermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") AclRolePermission record, @Param("example") AclRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int updateByExample(@Param("record") AclRolePermission record, @Param("example") AclRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(AclRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE_PERMISSION
     *
     * @mbggenerated Fri May 15 13:34:04 GMT+08:00 2020
     */
    int updateByPrimaryKey(AclRolePermission record);
}