package com.tmdrk.shiro.mapper;

import com.tmdrk.shiro.entity.AclRole;
import com.tmdrk.shiro.entity.AclRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AclRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int countByExample(AclRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int deleteByExample(AclRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int insert(AclRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int insertSelective(AclRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    List<AclRole> selectByExample(AclRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    AclRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") AclRole record, @Param("example") AclRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int updateByExample(@Param("record") AclRole record, @Param("example") AclRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(AclRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int updateByPrimaryKey(AclRole record);
}