package com.tmdrk.shiro.mapper;

import com.tmdrk.shiro.entity.AclUserRole;
import com.tmdrk.shiro.entity.AclUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AclUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_USER_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int countByExample(AclUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_USER_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int deleteByExample(AclUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_USER_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_USER_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int insert(AclUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_USER_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int insertSelective(AclUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_USER_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    List<AclUserRole> selectByExample(AclUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_USER_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    AclUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_USER_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") AclUserRole record, @Param("example") AclUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_USER_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int updateByExample(@Param("record") AclUserRole record, @Param("example") AclUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_USER_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(AclUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACL_USER_ROLE
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    int updateByPrimaryKey(AclUserRole record);
}