package org.tmdrk.toturial.mybatis.mapper;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.tmdrk.toturial.mybatis.entity.AceUser;
import org.tmdrk.toturial.mybatis.entity.AceUserExample;

import java.util.List;

public interface AceUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int countByExample(AceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int deleteByExample(AceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int insert(AceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int insertSelective(AceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    List<AceUser> selectByExample(AceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
//    @Select("SELECT id ,user_name FROM ACE_USER WHERE id = #{id}") //xml配置了，这里在配置会报错
    AceUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") AceUser record, @Param("example") AceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int updateByExample(@Param("record") AceUser record, @Param("example") AceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(AceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int updateByPrimaryKey(AceUser record);

    AceUser selectByIdSTATEMENT(@Param("id")Integer id);

    AceUser selectByIdPREPARED(Integer id);
}