package com.tmdrk.mycat.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.id
     *
     * @mbggenerated Mon May 18 18:51:24 GMT+08:00 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.user_name
     *
     * @mbggenerated Mon May 18 18:51:24 GMT+08:00 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.password
     *
     * @mbggenerated Mon May 18 18:51:24 GMT+08:00 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.idcard
     *
     * @mbggenerated Mon May 18 18:51:24 GMT+08:00 2020
     */
    private String idcard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.id
     *
     * @return the value of T_USER.id
     *
     * @mbggenerated Mon May 18 18:51:24 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.id
     *
     * @param id the value for T_USER.id
     *
     * @mbggenerated Mon May 18 18:51:24 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.user_name
     *
     * @return the value of T_USER.user_name
     *
     * @mbggenerated Mon May 18 18:51:24 GMT+08:00 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.user_name
     *
     * @param userName the value for T_USER.user_name
     *
     * @mbggenerated Mon May 18 18:51:24 GMT+08:00 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.password
     *
     * @return the value of T_USER.password
     *
     * @mbggenerated Mon May 18 18:51:24 GMT+08:00 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.password
     *
     * @param password the value for T_USER.password
     *
     * @mbggenerated Mon May 18 18:51:24 GMT+08:00 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.idcard
     *
     * @return the value of T_USER.idcard
     *
     * @mbggenerated Mon May 18 18:51:24 GMT+08:00 2020
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.idcard
     *
     * @param idcard the value for T_USER.idcard
     *
     * @mbggenerated Mon May 18 18:51:24 GMT+08:00 2020
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }
}