package com.tmdrk.ace.admin.mapper;

import com.tmdrk.ace.admin.entity.AceMenu;
import com.tmdrk.ace.admin.entity.AceMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AceMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_MENU
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int countByExample(AceMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_MENU
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int deleteByExample(AceMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_MENU
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_MENU
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int insert(AceMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_MENU
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int insertSelective(AceMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_MENU
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    List<AceMenu> selectByExample(AceMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_MENU
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    AceMenu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_MENU
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") AceMenu record, @Param("example") AceMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_MENU
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int updateByExample(@Param("record") AceMenu record, @Param("example") AceMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_MENU
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(AceMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_MENU
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int updateByPrimaryKey(AceMenu record);
}