package com.tmdrk.ace.admin.mapper;

import com.tmdrk.ace.admin.entity.AceUser;
import com.tmdrk.ace.admin.entity.AceUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AceUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int countByExample(AceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int deleteByExample(AceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int insert(AceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int insertSelective(AceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    List<AceUser> selectByExample(AceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    AceUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") AceUser record, @Param("example") AceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int updateByExample(@Param("record") AceUser record, @Param("example") AceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(AceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACE_USER
     *
     * @mbggenerated Thu May 07 13:21:20 GMT+08:00 2020
     */
    int updateByPrimaryKey(AceUser record);
}