package com.tmdrk.ace.admin.mapper;

import com.tmdrk.ace.admin.entity.OmpAddress;
import com.tmdrk.ace.admin.entity.OmpAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmpAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omp_address
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    int countByExample(OmpAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omp_address
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    int deleteByExample(OmpAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omp_address
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omp_address
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    int insert(OmpAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omp_address
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    int insertSelective(OmpAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omp_address
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    List<OmpAddress> selectByExample(OmpAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omp_address
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    OmpAddress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omp_address
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    int updateByExampleSelective(@Param("record") OmpAddress record, @Param("example") OmpAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omp_address
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    int updateByExample(@Param("record") OmpAddress record, @Param("example") OmpAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omp_address
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    int updateByPrimaryKeySelective(OmpAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table omp_address
     *
     * @mbggenerated Tue Jan 19 14:36:52 CST 2021
     */
    int updateByPrimaryKey(OmpAddress record);

}