package com.tmdrk.chat.dao.entity;

public class ChatUserFriend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER_FRIEND.id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER_FRIEND.user_id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER_FRIEND.friend_id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private Integer friendId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER_FRIEND.id
     *
     * @return the value of CHAT_USER_FRIEND.id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER_FRIEND.id
     *
     * @param id the value for CHAT_USER_FRIEND.id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER_FRIEND.user_id
     *
     * @return the value of CHAT_USER_FRIEND.user_id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER_FRIEND.user_id
     *
     * @param userId the value for CHAT_USER_FRIEND.user_id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER_FRIEND.friend_id
     *
     * @return the value of CHAT_USER_FRIEND.friend_id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER_FRIEND.friend_id
     *
     * @param friendId the value for CHAT_USER_FRIEND.friend_id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }
}