package com.tmdrk.chat.dao.entity;

public class ChatUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER.id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER.user_name
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER.password
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER.nick_name
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER.head_img_url
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private String headImgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER.id
     *
     * @return the value of CHAT_USER.id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER.id
     *
     * @param id the value for CHAT_USER.id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER.user_name
     *
     * @return the value of CHAT_USER.user_name
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER.user_name
     *
     * @param userName the value for CHAT_USER.user_name
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER.password
     *
     * @return the value of CHAT_USER.password
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER.password
     *
     * @param password the value for CHAT_USER.password
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER.nick_name
     *
     * @return the value of CHAT_USER.nick_name
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER.nick_name
     *
     * @param nickName the value for CHAT_USER.nick_name
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER.head_img_url
     *
     * @return the value of CHAT_USER.head_img_url
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER.head_img_url
     *
     * @param headImgUrl the value for CHAT_USER.head_img_url
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl == null ? null : headImgUrl.trim();
    }
}