package com.tmdrk.chat.dao.entity;

public class ChatUserMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER_MESSAGE.id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER_MESSAGE.from_id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private Integer fromId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER_MESSAGE.to_id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private Integer toId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER_MESSAGE.message
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER_MESSAGE.message_type
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private Byte messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER_MESSAGE.status
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHAT_USER_MESSAGE.create_time
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    private Integer createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER_MESSAGE.id
     *
     * @return the value of CHAT_USER_MESSAGE.id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER_MESSAGE.id
     *
     * @param id the value for CHAT_USER_MESSAGE.id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER_MESSAGE.from_id
     *
     * @return the value of CHAT_USER_MESSAGE.from_id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER_MESSAGE.from_id
     *
     * @param fromId the value for CHAT_USER_MESSAGE.from_id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER_MESSAGE.to_id
     *
     * @return the value of CHAT_USER_MESSAGE.to_id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER_MESSAGE.to_id
     *
     * @param toId the value for CHAT_USER_MESSAGE.to_id
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER_MESSAGE.message
     *
     * @return the value of CHAT_USER_MESSAGE.message
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER_MESSAGE.message
     *
     * @param message the value for CHAT_USER_MESSAGE.message
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER_MESSAGE.message_type
     *
     * @return the value of CHAT_USER_MESSAGE.message_type
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public Byte getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER_MESSAGE.message_type
     *
     * @param messageType the value for CHAT_USER_MESSAGE.message_type
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setMessageType(Byte messageType) {
        this.messageType = messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER_MESSAGE.status
     *
     * @return the value of CHAT_USER_MESSAGE.status
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER_MESSAGE.status
     *
     * @param status the value for CHAT_USER_MESSAGE.status
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHAT_USER_MESSAGE.create_time
     *
     * @return the value of CHAT_USER_MESSAGE.create_time
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHAT_USER_MESSAGE.create_time
     *
     * @param createTime the value for CHAT_USER_MESSAGE.create_time
     *
     * @mbggenerated Wed May 13 00:49:04 GMT+08:00 2020
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }
}