package com.tmdrk.shiro.entity;

public class AclUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACL_USER_ROLE.id
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACL_USER_ROLE.user_id
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACL_USER_ROLE.role_id
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACL_USER_ROLE.id
     *
     * @return the value of ACL_USER_ROLE.id
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACL_USER_ROLE.id
     *
     * @param id the value for ACL_USER_ROLE.id
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACL_USER_ROLE.user_id
     *
     * @return the value of ACL_USER_ROLE.user_id
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACL_USER_ROLE.user_id
     *
     * @param userId the value for ACL_USER_ROLE.user_id
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACL_USER_ROLE.role_id
     *
     * @return the value of ACL_USER_ROLE.role_id
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACL_USER_ROLE.role_id
     *
     * @param roleId the value for ACL_USER_ROLE.role_id
     *
     * @mbggenerated Thu May 14 22:52:55 GMT+08:00 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}